Profile header displays followers and following count
MediaTo-SDP/MediaTo pull request #124
Opened 2023-04-14 15:01 UTC by simone-kalbermatter

This PR changes the profile header:
- The edit button was moved next to the profile picture and changed to a round edit button, given that it only edits the profile picture anyways.
- The header now displays a _Following_ and _Followers_ button, with the number of following/follower users.

<img src="https://user-images.githubusercontent.com/71314469/232101350-6143af91-aa44-4afa-a982-ae275795ee70.png" width=30% height=30%>

The fragment to display the Following users already existed, and now appears on click of the Following button.
I added another fragment to display the Followers users, which is very similar to the existing following fragment, but does not display buttons for following or unfollowing the displayed users:

<img src="https://user-images.githubusercontent.com/71314469/232101353-a5bbc18a-2d81-44f6-8c45-355e183cbd39.png" width=30% height=30%>

2023-04-15 13:10 UTC, MeKHell requested changes
Few comments. Good job.

2023-04-15 22:59 UTC, simone-kalbermatter commented on app/src/main/java/com/github/sdp/mediato/model/User.java
> +            }
I think it is implemented like this because the database cannot store lists but only maps. So we are translating the database representation here.

2023-04-15 23:26 UTC, simone-kalbermatter commented on app/src/main/java/com/github/sdp/mediato/utility/adapters/UserAdapter.java
> +    public UserAdapter(UserViewModel userViewModel, Fragment fragment) {
Good point I added an adapter `UserFollowAdapter` that extends `UserAdapter` and displays the follow/unfollow button.

2023-04-16 17:44 UTC, MeKHell commented on app/src/main/java/com/github/sdp/mediato/model/User.java
> +            }
Sounds legitimate

2023-04-16 17:46 UTC, MeKHell approved these changes
LGTM. Great job 👍

2023-04-16 18:01 UTC, merged