Sign-out feature
MediaTo-SDP/MediaTo pull request #142
Opened 2023-04-25 08:10 UTC by PH-14

This PR adds a sign-out button on the profile page in order to sign out the user and redirect him/her towards the authentication activity.

2023-04-25 13:57 UTC, simone-kalbermatter requested changes
LGTM, clean work and good tests. Just a few comments. And I think there is some formatting issue because some full files are shown as diff.

2023-04-25 13:57 UTC, simone-kalbermatter commented on app/src/main/java/com/github/sdp/mediato/ui/MyProfileFragment.java
> +        signOutButton.setOnClickListener(v -> {((MainActivity) getActivity()).signOutUser();});
I think the curly braces here are not needed

2023-04-25 13:57 UTC, simone-kalbermatter commented on app/src/main/res/layout/layout_profile_header.xml
> +  <Button
Could you change the color and size of the button to make it a bit less eye catching for a sign out button 😄 And maybe change the text to _sign out_ or just a sign out icon to make it a bit more clear what the button does.

2023-04-25 13:57 UTC, simone-kalbermatter commented on app/src/main/res/layout/layout_profile_header.xml
> +      android:layout_height="50dp"
It would be better to use `"wrap_content"` instead of hardcoding the button size.

2023-04-26 06:32 UTC, MeKHell reviewed
I do not know what soft you use to commit your change, but it is pretty hard to know what you changed and what you did not.

2023-04-26 06:32 UTC, MeKHell commented on app/src/main/java/com/github/sdp/mediato/ui/MyProfileFragment.java
> +        collectionListRecyclerView = view.findViewById(R.id.collection_list_recycler_view);
You might want to look into binders to remove the need of these lines.

2023-04-26 18:07 UTC, simone-kalbermatter approved these changes
LGTM!

2023-04-26 18:07 UTC, merged